baseURL = "https://a4ism.news/"
title = "a4ism.news"
author = "RND"
copyright = "© 2021, Real News Distributions (RND)"
paginate = 4
languageCode = "en-AU"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "origin"

[params]
  description = "just some real news 📰"
  header_image = "images/a4ism.jpeg"
  slogan = "$ grep -rni \"The how's and why's\" ."
  SEOTitle = "a4ism.news - perspective on real news."
  keyword = "real news, not fake news, back to back, rnd"
  featured = true
  cssonly = false

  [params.socials]
    email = "mailto:hello@a4ism.news"
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = "https://github.com/a4ism-news/"
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = ""
    medium= ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

  [markup.goldmark.renderer]
      unsafe = true

