baseURL = "https://a4ism.news/"
title = "a4ism.news"
author = "RND"
copyright = "Real News Distributions (RND) © 2021"
paginate = 4
languageCode = "en-AU"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "origin"

[Author]
    name = "RND"

[params]
  description = "just some real news 📰"
  DateForm = "02 Jan 2006"
  header_image = "images/a4ism.jpeg"
  slogan = "a4ism.news - perspective(s) on real news."
  SEOTitle = "a4ism.news - perspective(s) on real news."
  keyword = "a4ism, a4ism.news, real news, not fake news, rnd, back to back"
  featured = true
  cssonly = false

  [params.socials]
    email = "mailto:hello@a4ism.news"
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = "https://github.com/a4ism-news/"
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = ""
    medium= ""

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 2

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

  [markup.goldmark.renderer]
      unsafe = true

